server:
    port: 80
    context-path: /
debug: false
#eureka:
#  client:
#   register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:9000/eureka/
#  instance:
#   preferIpAddress: true
#   instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#   lease-expiration-duration-in-seconds: 30
#    lease-renewal-interval-in-seconds: 15 
management:
  security:
    enabled: false
spring:
    application:
      name: agent-service
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request
    redis:
      host: 120.79.129.165
      password: zyjy123456
      port: 6379
    datasource:
      url: jdbc:mysql://gz-cdb-jm6bdf98.sql.tencentcdb.com:63946/db_flink
      username: root
      password: Mcfish2017&&
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    aop:
      auto: true
    data:
      mongodb:
        uri: mongodb://admin:admin@116.62.206.158:27017/admin
mybatis:
    type-aliases-package: com.mcfish.common.model
    mapper-locations: classpath:com/mcfish/common/mapping/*.xml
mapper:
    mappers:
        - com.mcfish.common.MyMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql